batch_size: 64
decoder_config:
  dropout: 0
  embedding_dim: 256
  hidden_size: 512
  input_size: 256
  num_embeddings: 79
  num_layers: 3
  pretrain: true
  pretrained_model: ../p2d_pretrained_models/rnn/pretrained_rnn_35_selfies.pt
  which_rnn: GRU
encoder_config:
  dim: 128
  num_channels: 3
  num_edge_attr: 1
  num_features: 11
  num_layers: 6
  pretrain: false
  pretrained_model: ../p2d_pretrained_models/gnn/trained_classifier_model_999.pt
  train_eps: true
excluded_pockets: ./data/excluded_pockets.yaml
features_to_use:
- x
- y
- z
- r
- theta
- phi
- sasa
- charge
- hydrophobicity
- binding_probability
- sequence_entropy
learning_rate: 0.003
num_epoch: 30
out_dir: ../p2d_results_selfie/cv_tune/cross_val_fold_0_run2/
pocket_dir: ../data/googlenet-dataset/
pop_dir: ../data/pops-googlenet/
seed: 666
smiles_dir: ./data/pocket-smiles.yaml
test_split: 0.05
vocab: selfies
vocab_path: ./vocab/selfies_merged_vocab.yaml
weight_decay: 0.0005