#!/bin/bash
#PBS -q workq
#PBS -l nodes=1:ppn=20
#PBS -l walltime=72:00:00
#PBS -A hpc_michal01
#PBS -j oe

cd /work/derick/siamese-monet-project/Pocket2Drug/cross_validation/subset/

mol_dir="../../../p2d_results_selfie/cv_results/cross_val_fold_${FOLD}/val_pockets_sample/"

out_dir="../../../p2d_results_selfie/cv_results/cross_val_fold_${FOLD}/val_pockets_sample_clustered/"

log_dir="./fold${FOLD}_log.txt"

singularity exec --nv -B /work,/project,/usr/lib64 /work/derick/singularities/pytorch171.simg python compute_subset.py -mol_dir ${mol_dir} -out_dir ${out_dir} > ${log_dir} 2>&1 

