"""
Plot the best docking scores of the molecules generated by the model
and the random molecules sampled from Zinc.
"""
import argparse
from os import listdir
from os.path import isfile, join
from tqdm import tqdm
import yaml
from statistics import mean


def get_args():
    parser = argparse.ArgumentParser("python")

    parser.add_argument("-model_mols_dir",
                        required=False,
                        default="../../../p2d_results_selfie/cv_results/cross_val_fold_0/val_pockets_docking_results/",
                        help="directory of docking scores of molecules generated by model")

    parser.add_argument("-zinc_mols_dir",
                        required=False,
                        default="../../../p2d_results_selfie/cv_results/cross_val_fold_0/zinc_sampled_docking_results/",
                        help="directory of docking scores of molecules sampled from Zinc")

    return parser.parse_args()

if __name__=="__main__":
    args = get_args()
    model_mols_dir = args.model_mols_dir
    zinc_mols_dir = args.zinc_mols_dir

    model_docking_score_files = [f for f in listdir(
                model_mols_dir) if isfile(join(model_mols_dir, f))]

    # tuples of docking scores
    all_model_docking_scores = []
    all_zinc_docking_scores = []
    num_problematic_pocket = 0
    print("loading docking scores...")
    for docking_file in tqdm(model_docking_score_files):
        # docking scores of model molecules 
        with open(join(model_mols_dir, docking_file), "r") as f:
            model_docking_scores = yaml.full_load(f)
            all_model_docking_scores.extend(list(model_docking_scores.values()))

        # docking scores of random zinc molecules
        with open(join(zinc_mols_dir, docking_file), "r") as f:
            zinc_docking_scores = yaml.full_load(f)
            all_zinc_docking_scores.extend(list(zinc_docking_scores.values()))

    print("loading finished, number of problematic pocket: ", num_problematic_pocket)

    print("mean model docking score: ", mean(all_model_docking_scores))
    print("mean zinc docking score: ", mean(all_zinc_docking_scores))



        