#!/bin/bash
#PBS -q workq
#PBS -l nodes=1:ppn=20
#PBS -l walltime=72:00:00
#PBS -A hpc_michal01
#PBS -j oe

source activate myenv

cd /work/derick/siamese-monet-project/Pocket2Drug/cross_validation_v1/docking/docking_script

log_path="/work/derick/siamese-monet-project/p2d_results_selfie/cv_results/docking_logs/zinc-ranked-mols-docking-fold${FOLD}-${START}-${END}"

python smina_model_dock.py -fold ${FOLD} -start ${START} -end ${END} > ${log_path} 2>&1
